### ISSUE TITLE
Java keywords in Enums

### ISSUE THREAD

**Issue by chel-man** [st-js/st-js#37]
Can we have annotation on Enums like @LoverCase  and @UpperCase or maybe better @RemoveSimbol(value="$") to generate js from Enums with java keywords.
```java
@RemoveSimbol(value="$")
enum WithKeywords {
   $boolean,$float;
}
```
generated 
```javascript
var WithKeywords = stjs.enumeration(
    "boolean",
    "float"
);
```

**Comment by npiguet** [comment]
Aren't most Java keywords also either JavaScript keywords or JavaScript future reserved keywords (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords).

Therefore if we did this, if would pretty much never be possible to refer to the special enum members using MyEnum.boolean, or MyEnum.float since both of these would result in syntax errors.

I don't think that this is a good idea.

**Comment by npiguet** [comment]
Can you please post a specific usecase in which this would be useful?

**Comment by npiguet** [comment]
Won't be implemented
