### ISSUE TITLE
Anonymous class instantiation losing it's type

### ISSUE THREAD

**Issue by gramacyan** [st-js/st-js#57]
When instantiating and overriding members or fields of a class it's type detail get lost.

Example:

```
public class DateWrapper {
   public Date internalDate;
   public long getMillis() {
      return internalDate.getTime();
   }
   public static long staticGetMillis(DateWrapper inst) {
      return inst.getMillis();
   }
   public static void main(String[] args) {
      staticGetMillis(new DateWrapper(){{
         internalDate = new Date();
      }});
   }
}
```

Throws error: getMillis is not defined.

The generator outputs:

```
DateWrapper.staticGetMillis({internalDate: new Date()});
```

Thus passing a untyped object to the static method. 
A more desired result might be: 

```
DateWrapper.staticGetMillis(stjs.copyProps({internalDate:new Date()}, new DateWrapper()));
```

OR via stjs.typefy

```
DateWrapper.staticGetMillis(stjs.typefy({internalDate:new Date()}, new DateWrapper()));
```

**Comment by npiguet** [comment]
Specifically, this is caused by the fact that ST-JS always translates the double braces notation {{ }} as an object literal. This is actually by design, but after seeing how this feature is used in live code by several different people, is a gotcha that may turn out not be such a good idea.

We should probably inspect the parent class of the anonymous class, and only generate an object literal if the parent class contains no instance methods or constructors (and also inherits none), but generate a full-blown anonymous class via stjs.extend() in the other case.

Anyway, a proper workaround for your case would be to add a contructor to your class, and pass this information as parameters.

**Comment by npiguet** [comment]
as mentionned by the OP, `stjs.typefy({property:"value"}, ParentClass)` could also be a nice solution for the case where the parent class has methods and/or is not annotated with `@SyntheticType`.

Note that I've definitely already seen this dodgy usage several times in the wild, so it is probably a good idea to protect against it.

**Comment by npiguet** [comment]
Note that using an anonymous class using a single pair or braces (ie: `{}` instead of `{{}}`) does maintain the type correctly.

**Comment by golanhall** [comment]
I also noticed that non-static initialisers are disallowed in regular class-constructs, throwing compilation errors. In contrast to this anonymous instantiation initialiser blocks are surprisingly allowed. 

Imho the compiler shouldn't treat both cases differently, halting compilation because a proper transpile can't be made due to language limitation are a good thing, preventing the developer to write illegal constructs. Maybe only allowing initialiser blocks for @SyntheticClass annotated types are a solution to this issue?
