### ISSUE TITLE
My Annotation won't be inserted

### ISSUE THREAD

**Issue by Tapsi** [st-js/st-js#60]
```
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface TestAnnotation {
  int value() default 0;
}
```

```
public class Unit {
  @TestAnnotation  public void outer() {
    int i = 1;
  }
}
```

```
stjs.ns("testNm");
testNm.TestAnnotation = function() {};
stjs.extend(testNm.TestAnnotation, null, [], function(constructor, prototype) {
    prototype.value = function() {};
}, {}, {});

stjs.ns("testNm");
testNm.Unit = function() {};
stjs.extend(testNm.Unit, null, [], function(constructor, prototype) {
    prototype.outer = function() {
        var i = 1;
    };
}, {}, {});
```

I used the 3.1.3 version of STJS. Do I missed something  ?

**Comment by acraciun** [comment]
Only annotations that are configured with the Maven plugin will be generated - in order to not clutter the client with useless metadata. RetentionPolicy.SOURCE will not be kept (RUNTIME is fine).

I updated the maven's plugin documentation - you need to add a configuration like this
<annotations>
<annotation>TestAnnotation</annotation>
</annotations>

Please note that the annotations class name does not contain the package, neither the namespace (this may be changed in a future version if it's problematic)

**Comment by Tapsi** [comment]
Thanks for the response =)
