### ISSUE TITLE
@SyntheticType classes are generated, but shouldn't

### ISSUE THREAD

**Issue by onigoetz** [st-js/st-js#70]
In my code I have a few classes annotated with @SyntheticType

The references to them are generated correctly (without mention of the class)
But the class itself is generated, this is pretty useless as the class isn't used anywhere.
Also it's added to the final artifact.

The workaround is to add Both "STJSBridge" and "SyntheticType"

**Comment by npiguet** [comment]
After lots of discussions, we have decided that @SyntheticType makes no sense as an annotation on its own. It is our opinion that @SyntheticType currently only makes sense when it used together with @STJSBridge or @JavaScriptFunction. 

Therefore, we will add a boolean `isSynthetic` (or something similar) in @STJSBridge to indicate that the bridged type doesn't really exist as a class (ex: AjaxParams and other option objects).

We will also update the usage of @JavascriptFunction so that it doesn't generate the annotated interface.

Finally, we will also fix Issue #57. With all of this, we believe @SyntheticType becomes useless and can be deprecated.

**Comment by onigoetz** [comment]
Thanks for the precisions, it gets a lot clearer now.
