### ISSUE TITLE
Wrong translation of multiple assignments in object initializer

### ISSUE THREAD

**Issue by o-nix** [st-js/st-js#78]
element.accordion(new AccordionOptions() {{
      activate = create = null;
    }})

processed into
    
    element.accordion({ activate: this.create = null })

which, I believe, is wrong, because of non reliable `this` in an in-place object initialization.

**Comment by npiguet** [comment]
The `{{}}` notation is supposed to emulate JavaScript Object litterals. The syntax you are trying to use is not supported by JavaScript object litterals, and therefore is not supported by ST-JS. 

In the future, ST-JS will throw an exception when you try to use fields from the object literal itself on the right hand side of the assignment (because this isn't allowed in JS either).

**Comment by o-nix** [comment]
:+1:
