### ISSUE TITLE
Function.arguments: incorrect handling for actual argument parameter with same name

### ISSUE THREAD

**Issue by prmx** [st-js/st-js#79]
```java
		public void doSmth(Long id, Object arguments) {
			Process process = findById(id);

			if (process != null) {
				process.args = arguments;
				process.ready = true;
			}
		}
```
will be compiled into
```javascript
        prototype.doSmth = function(id, _arguments) {
            var process = this.findById(id);
            if (process != null) {
                process.args = arguments;
                process.ready = true;
            }
        };
```

At this example we will lose arguments value.

This special case handled by compiler, but only for method signature (adding '_' prefix), just need additionally handle all method references to this argument.

**Comment by npiguet** [comment]
This is caused by the fact the `arguments` is a special variable in JavaScript that is defined by default in every method and is an Array-like object that contains the values of all the arguments to the method. ST-JS tries to handle the conflict between a parameter called `arguments` and the `arguments` special variable. The logic is a little bit complicated, but it can be summarized as such:

You can only have a method parameter called `arguments` if is the only parameter of the method.

Currently the ST-JS compiler assumes that you know this. Instead, it should throw an error with a clear error message.

A solution to your problem is: Just rename `arguments` to `args` and everything will be fine
