### ISSUE TITLE
Deprecate @SyntheticType

### ISSUE THREAD

**Issue by onigoetz** [st-js/st-js#86]
See comment by @npiguet in #70

**Comment by acraciun** [comment]
in fact you may have synthetic types in in your code (that's not a bridge) because some libraries require you to do so - or simply because you want a cleaner JS code.

Both @STJSBridge and @SyntheticType do exactly what you expect from them:
- first annotates classes that represent libraries done in JS (some of these classes may exist as in the libraries - eg Promise, some may not exist eg all jQuery plugin options
- the second annotates classes that are created to provide type info whenever you use in JS simple objects {}. These may be in a bridge or not.
