### ISSUE TITLE
Feature request: Allow methods with @Template("toProperty") for object creation blocks

### ISSUE THREAD

**Issue by micw** [st-js/st-js#94]
Currently an object creation block is only allowed for properties. There's a template "toProperty" that creates js properties from java methods these should also be allowed within object creation blocks.

Example:

class MyData {
  @Template("toProperty")
  public native void myprop1(String value);

  public String myprop2;
}

Should allow definitions as:

new MyData() {{
  myprop1("prop1");
  myprop2="prop2";
}}

**Comment by micw** [comment]
Great work, thank you a lot!

But is it really a good idea to check for the "toProperty" template name?

**Comment by npiguet** [comment]
Well this particular one is part of the core templates and the 
correspondance between the template name and it's implementation is already 
hard-coded somewhere else in the generator, so it doesn't seem like much of 
a problem right now.

It might be a bit nicer to move the template names to their respective 
classes instead of leaving those strings hard-coded in unrelated classes, 
but for now that'll do.
